### ISSUE TITLE
Since no one is responding, here is another baddie

### ISSUE THREAD

**Issue by cglenn7777** [sarahavilov/Autofill-Forms#14]
I wrote my comment first at http://www.lamy.com/content/services/contact_us/index_eng.html#e1109, then I clicked on the pencil icon.   IT REPLACED MY COMMENT WITH MY EMAIL ADDRESS!  All other fields, including email address, were correctly completed.  Now back to re-create my comment...

**Comment by sarahavilov** [comment]
You could just use ctrl+z to have your comment back.

It seems you have defined a custom rule and that rule somehow matches the comment box. Please confirm the problem on a clean profile, http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by cglenn7777** [comment]
Do you have instructions for a Mac?

**Comment by sarahavilov** [comment]
Just close all your Firefox windows (Command + Q). Now run the command provided in the example section of the blog post. This way you can create a new profile. Note that you can always get back to the original profile by repeating these steps.

**Comment by cglenn7777** [comment]
Sorry, I thought you want to hear about problems people run into when using your app.  Thanks for making it.  I'm not a power user.

**Comment by sarahavilov** [comment]
Creating a new profile is not that hard. Anyway, if you any question regarding on how to create a new profile you can share it here and I'll try to help.
