### ISSUE TITLE
Android support? Is there ANY way to autofill forms with preset data on android/Firefox? 

### ISSUE THREAD

**Issue by Penticton** [sarahavilov/Autofill-Forms#17]
This addon appears on the Firefox android addon page but refuses to install.

Can someone assist me with this?
If not, can you direct me to a suitable addon which will allow me to autofill Web forms like Chrome does? (CHROME'S VERSION SHOWN IN ATTACHED SCREENSHOT)
![tmp_11336-img_20160401_0915511865911104](https://cloud.githubusercontent.com/assets/18225108/14224418/6cec2e84-f850-11e5-8146-228be99b4d1a.jpg)

Thanks.

**Comment by sarahavilov** [comment]
Sorry this extension is not compatible with Firefox for Android. Try to open https://addons.mozilla.org/en-US/firefox/ on an Android device to see all compatible extensions. I am not sure if there is any autofill extension available for Android yet.
