### ISSUE TITLE
Support for RandExp.js

### ISSUE THREAD

**Issue by icaine** [sarahavilov/Autofill-Forms#23]
Hi, 
it would be great if u could implement support for https://fent.github.io/randexp.js/
E.g. when you type something like `/SomeRandExp/i` to field's value it will generate a value accordingly to the expression.

**Comment by sarahavilov** [comment]
We can have this on [AutoFill Forms (e10s)](https://addons.mozilla.org/en-US/firefox/addon/autofill-forms-e10s/). However, I need a more simple library. `randexp.js` has two dependencies and it would be really hard to submit this library for review. AMO does not accept minified JS code.

**Comment by icaine** [comment]
Would this help (https://gist.github.com/icaine/e85ad1a6a0d3f5fad8f7a3f5e5649617)? Its full version with dependecies included.

**Comment by sarahavilov** [comment]
I wasn't able to generate random string using the gist function. Please try to fix the bug during string generation.

For now I am using https://github.com/cho45/String_random.js

To try the lastest dev version download https://github.com/sarahavilov/autofillforms-e10s/blob/master/builds/packed/firefox.xpi?raw=true and use about:Debugging to load the extension.

**Comment by icaine** [comment]
I cant see a problem? https://jsfiddle.net/trsy4rhe/

**Comment by icaine** [comment]
Update: from string https://jsfiddle.net/trsy4rhe/2/

**Comment by sarahavilov** [comment]
Have you tried the dev XPI? Did you have any issue with the library I have used? Should I consider switching to `randexp.js`? The one I have used is simpler so I prefer to stick to it unless there is an issue

**Comment by sarahavilov** [comment]
To make `randexp.js` compatible with AutoFill Forms e10s please follow these guidelines
1. define `var randexp = randexp || exports;` on top of the file; example: https://github.com/sarahavilov/autofillforms-e10s/blob/master/src/lib/regtools.js#L2
2. function should return `randexp.gen = function (pattern) {...}`; example https://github.com/sarahavilov/autofillforms-e10s/blob/master/src/lib/regtools.js#L4
3. Instead of https://gist.github.com/icaine/e85ad1a6a0d3f5fad8f7a3f5e5649617#file-randexp-full-js-L941-L947 we can have `randexp.gen = obj`

Calling `randexp.gen(pattern)` should return a random string.

**Comment by icaine** [comment]
The only problem with String_random is that it does not support moddifier 'i'.

XPI worked, but string generation with randexp did not..

**Comment by sarahavilov** [comment]
> XPI worked, but string generation with randexp did not..

So the XPI works fine with String_random, right? Please share randexp file you have used for debugging.

Do we really need to support "i" modifier? for instance you can simply rewrite `/o+/i` with `/[oO]+/`

**Comment by icaine** [comment]
Sry, i meant i was able to run xpi (with current code - String_random) but it returns the pattern itself and not random string.

**Comment by sarahavilov** [comment]
what is the RegExp you have used?

**Comment by icaine** [comment]
I used the link you provided me:) So what is there is what didnt work.

**Comment by sarahavilov** [comment]
No I meant what regular expression you have used in the value input box

**Comment by sarahavilov** [comment]
By default there is no regular expression is defined in the value boxes so you need to provide one in order for the extension to use it.

**Comment by icaine** [comment]
https://jsfiddle.net/sa2b1fjn/ - RandExp embedded in your regtools.js (beware i had to replace `exports` with `[]`).

I tried `/[a-d] (pan|jan|van) \w{5}/` as `first-name`

**Comment by sarahavilov** [comment]
I just tried your expression in http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_form_submit and it worked just fine for `first-name`. Please open error console and then press autofill to see if you get a new error in the console or not.

**Comment by sarahavilov** [comment]
error console (Ctrl + Shift + J)

**Comment by icaine** [comment]
No error at all, but i should mention i have FF47 only (maybe that is the problem)?

**Comment by icaine** [comment]
PS: i suggest to use this (https://jsfiddle.net/sa2b1fjn/1/)

```
var patternParts = /^\/(.*)\/(i?)$/;
var matches = patternParts.exec(pattern)
return new RandExp(matches[1], matches[2]).gen();
```

instead of

```
return new RandExp(pattern).gen();
```

**Comment by sarahavilov** [comment]
how about this version; https://github.com/sarahavilov/autofillforms-e10s/blob/master/builds/packed/firefox.xpi?raw=true

**Comment by sarahavilov** [comment]
> PS: i suggest to use this (https://jsfiddle.net/sa2b1fjn/1/)

I still prefer to stick with `String_random.js` as it is simpler that `RandExp`.

> return new RandExp(pattern).gen();

done thanks; https://github.com/sarahavilov/autofillforms-e10s/blob/master/src/lib/background.js#L108

**Comment by icaine** [comment]
String_random doesnt have https://github.com/fent/randexp.js#default-range which probably should be part of some config:)

**Comment by sarahavilov** [comment]
So the new XPI worked for you?

**Comment by icaine** [comment]
Nope same thing - returns pattern instead of generated string (https://db.tt/rL6NRCt9)

**Comment by sarahavilov** [comment]
okay then try with `/\w{5,8}/` instead

Yours working fine for me though. Are you sure you have downloaded the XPI again?

**Comment by icaine** [comment]
i have tried both..

and ye i unistalled the old one and installed new one.

**Comment by sarahavilov** [comment]
Okay then lets see what is going wrong. Try https://www.dropbox.com/s/qrt6jnkdiewz8tq/firefox.xpi?dl=0 version.

Open Error Console. You should get an output like this when autofill is clicked
![screen shot 2016-07-03 at 15 16 42](https://cloud.githubusercontent.com/assets/12985412/16545022/54251094-4131-11e6-9a8a-d8462d0ccd68.png)

**Comment by icaine** [comment]
Hmm i figured out why it doesnt work.. i was using it via context menu, not the autofill button.. Works now..

**Comment by sarahavilov** [comment]
I see! It is fixed now. Thanks for the report.

**Comment by icaine** [comment]
Great:) Seems like its done then? close?:)

**Comment by sarahavilov** [comment]
Great! Thanks for your contribution

**Comment by icaine** [comment]
Thank you!;)
