### ISSUE TITLE
Autofill Forms could not be verified for use in firefox and has been disabled

### ISSUE THREAD

**Issue by ildar-aim** [sarahavilov/Autofill-Forms#25]
![screenshot_2016-08-10_10-01-30](https://cloud.githubusercontent.com/assets/1235868/17543395/762b0afe-5ee1-11e6-8bd7-c6ad45ad9c57.png)

FF 48.0

**Comment by sarahavilov** [comment]
You must have a developer version of AF. Try to get it one more time from AMO
