### ISSUE TITLE
Auto-fill not really working much

### ISSUE THREAD

**Issue by cglenn7777** [sarahavilov/Autofill-Forms#3]
For the past few years, I used Google Chrome, so I have an idea about what percent of sites allow auto-complete, and how auto-complete in general should work.  I switched to Firefox and added this add-on about three months ago.  It's not learning, and it's not auto-completing.  Occasionally, my email address will auto-complete, but not much else.

Even the registration page for this forum did not autofil my email address.  *I have all my basic info entered on the autofil settings, yet almost all sites don't auto-complete.*

Using my mouse left-handed, I could left click when in each form field and select which to enter, but it's easier to just enter it.

PS:  I just used a site with a form.  I expected that I would go the the first field, type the first letter, then auto complete would fill in that field *and all the others* as Chrome did.  In fact, I had to enter the first letter of one field, select the correct and only response in the drop down, go the the next field, do the same for each field, one by one.  But only some fields allowed autocomplete, even though all field info is in my settings.  It did first and last name.  It did not do state, zip code, or email.  Street address was not asked for.

**Comment by cglenn7777** [comment]
Is this forum still monitored?

**Comment by cglenn7777** [comment]
where am i supposed to ask for help?

**Comment by sarahavilov** [comment]
Yes, I am kind of busy. Will respond soon.

**Comment by sarahavilov** [comment]
Well, Autofill-Forms has not been maintained for a while and most probably some new tags are not working in the extension anymore. If you have a case please submit that particular form and I will take a look at what tags are not supported.

**Comment by cglenn7777** [comment]
Thanks sarahavilov for the reply.  I think I'll just open google chrome when I need to complete a form.
