### ISSUE TITLE
Autofill forms not working in Firefox 53.0

### ISSUE THREAD

**Issue by ibcs01** [sarahavilov/Autofill-Forms#31]
Hi,

We use this plugin daily and it has always worked very well.
But today we received an upgrade from Firefox (53.0) and we can no longer see profiles nor import profiles.
When downgrading to Firefox 52.0.2, everything works fine again.
But of course we would like to keep Firefox at the latest version, for understandable reasons.

If you can find the time, could you please resolve this issue?

Thanks your the support!

**Comment by ibcs01** [comment]
After removing and reinstalling Firefox completely, the issue seems resolved.

**Comment by dondrr** [comment]
WHY are you sending this email to me????? And it is being sent to me over
and over again?????
